replicaCount: 1

image:
  repository: postgres
  tag: "13.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

resources: {}

