apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      nodePort: 31432
  selector:
    app: postgres
